In [4]:
import numpy as np
import pandas as pd

set= pd.read_csv("raw_data.csv")

In [10]:
set
set1=set.copy()
set1
#missing val's
# data types 
#dup's
#strings

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [12]:
set1.isnull().sum()
#missing val's
# data types 
#dup's
#strings

id         0
name       1
age        3
country    1
gender     1
income     1
dtype: int64

In [21]:
set1["name"]=set1["name"].fillna("hey")
set1["name"]

0         John Doe
1         John Doe
2       Jane Smith
3             Alex
4     Maria Garcia
5           Li Wei
6              hey
7       Ahmed Khan
8       Rachel Lee
9      Carlos Ruiz
10     Emily Davis
Name: name, dtype: object

In [45]:
# missing age by mean of all ages 
salary_mean= set1["age"].mean()
set1["age"]=set1["age"].ffill().astype("int64")
set1["income"]= set1["income"].fillna(age_mean)

set1["gender"]=set1["gender"].ffill()

set1.bfill(inplace=True)
####### *********************************
set1.loc[set1["gender"]== "Unknown","gender"]="trans"


#set1["gender"]=set1["gender"].fillna({
 #   "gender":"trans"  })
set1[["income","age","gender","country"]]

          income  age  gender country
0   55000.000000   29    Male     USA
1   55000.000000   29    Male     USA
2   62000.000000   29  Female  Canada
3   47000.000000   29   trans     USA
4      31.727273   34  Female   Spain
5   51000.000000   27    Male   China
6   73000.000000   45  Female   India
7   68000.000000   38    Male     USA
8   62000.000000   29  Female     USA
9   45000.000000   29    Male  Mexico
10  58000.000000   31    Male     USA

In [61]:
print(set1.isnull().sum())

set1.duplicated()
print(set1.drop_duplicates())

set1.duplicated()

id         0
name       0
age        0
country    0
gender     0
income     0
dtype: int64
    id          name  age country  gender        income
0    1      John Doe   29     USA    Male  55000.000000
2    2    Jane Smith   29  Canada  Female  62000.000000
3    3          Alex   29     USA   trans  47000.000000
4    4  Maria Garcia   34   Spain  Female     31.727273
5    5        Li Wei   27   China    Male  51000.000000
6    6           hey   45   India  Female  73000.000000
7    7    Ahmed Khan   38     USA    Male  68000.000000
8    8    Rachel Lee   29     USA  Female  62000.000000
9    9   Carlos Ruiz   29  Mexico    Male  45000.000000
10  10   Emily Davis   31     USA    Male  58000.000000

0     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
dtype: bool

In [73]:
## handling strings 
print(set1["country"].str.upper())

print(set1["country"].str.lower())

print(set1["name"].str.split(" "))
print(set1["name"].str.strip())

print(set1["name"].str.contains("Bob",  case=False))

0        USA
2     CANADA
3        USA
4      SPAIN
5      CHINA
6      INDIA
7        USA
8        USA
9     MEXICO
10       USA
Name: country, dtype: object
0        usa
2     canada
3        usa
4      spain
5      china
6      india
7        usa
8        usa
9     mexico
10       usa
Name: country, dtype: object
0         [John, Doe]
2       [Jane, Smith]
3              [Alex]
4     [Maria, Garcia]
5           [Li, Wei]
6               [hey]
7       [Ahmed, Khan]
8       [Rachel, Lee]
9      [Carlos, Ruiz]
10     [Emily, Davis]
Name: name, dtype: object
0         John Doe
2       Jane Smith
3             Alex
4     Maria Garcia
5           Li Wei
6              hey
7       Ahmed Khan
8       Rachel Lee
9      Carlos Ruiz
10     Emily Davis
Name: name, dtype: object
0     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
Name: name, dtype: bool

In [49]:
set1

    id          name  age country  gender        income
0    1      John Doe   29     USA    Male  55000.000000
1    1      John Doe   29     USA    Male  55000.000000
2    2    Jane Smith   29  Canada  Female  62000.000000
3    3          Alex   29     USA   trans  47000.000000
4    4  Maria Garcia   34   Spain  Female     31.727273
5    5        Li Wei   27   China    Male  51000.000000
6    6           hey   45   India  Female  73000.000000
7    7    Ahmed Khan   38     USA    Male  68000.000000
8    8    Rachel Lee   29     USA  Female  62000.000000
9    9   Carlos Ruiz   29  Mexico    Male  45000.000000
10  10   Emily Davis   31     USA    Male  58000.000000